name: Build Client & Server

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Client
        run: yarn workspace client build

      - name: Build Server
        run: yarn workspace server build
