name: Lint & Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Lint & Format
        run: yarn lint
