name: Deploy Preview

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    needs: [build, lint]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --token ${{ secrets.VERCEL_TOKEN }} --yes --scope=your-team-name --env NODE_ENV=production --build-env NODE_ENV=production --prod

      - name: Post Deployment URL
        run: echo "Deployed Preview: $(vercel --token ${{ secrets.VERCEL_TOKEN }})"

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "🚀 Preview Deployed! Check it here: [Preview URL](https://your-vercel-url.vercel.app)"
